### ISSUE TITLE
My doubts 

### ISSUE THREAD

**Issue by creepyGoose** [Savinvadim1312/AirbnbClone#3]
```
Parsing error: Unexpected token
   7 |   const navigation = useNavigation();
   8 |     return {
>  9 |          <View>
     |          ^
  10 |            <Pressable
  11 |           style = {styles.searchButton}
  12 |           onPress={() => console.warn('Search Btn clicked')}>
```

I got this error on VS Code, and I don't know how to fix it. It's preventing to run the project

**Comment by VadimNotJustDev** [comment]
on line 8, it should be `return (`. It's a round bracket.

**Comment by eueid** [comment]
Thanks a lot..

now i'm getting this other error

`info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
C:\Users\lucas\Documents\Airbnb\node_modules\jetifier\bin\jetify:3
nprequire('../index');
^

ReferenceError: nprequire is not defined
    at Object.<anonymous> (C:\Users\lucas\Documents\Airbnb\node_modules\jetifier\bin\jetify:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Failed to run jetifier. Run CLI with --verbose flag for more details.
Error: Command failed: C:\Users\lucas\Documents\Airbnb\node_modules\jetifier\bin\jetify
    at makeError (C:\Users\lucas\Documents\Airbnb\node_modules\execa\index.js:174:9)`
